### ISSUE TITLE
3D Biomes

### ISSUE THREAD

**Issue by devmattrick** [SpongePowered/Schematic-Specification#16]
Since 1.15, the way biomes are stored has changed. Where biomes used to be an array of 256 integers (one for every x, z position in a chunk), it is now stored as an array of 1024 integers (each integer represents a 4x4x4 section of of the chunk).

This is now being put to use in vanilla Minecraft where there are "3D biomes" in the Nether. Additionally, this causes an issue for tools that are updated to 1.15 since they can no longer set biomes for each x,z coordinate and can only set them for 4x4 sections. As such, I feel it may be justified to update the format to support the new biome storage mechanism.

While the revision is rather small, it would unfortunately justify a version bump as it will cause breaking changes to the format. This involves changing the indexing of the Biomes varint array to be 3-dimensional. However, since biomes are all of a size 4x4x4, but schematics can be pasted on a scale of 1x1x1 this presents a challenge for tools that will be pasting and loading schematics.

**Comment by gabizou** [comment]
I'll definitely version bump for 3D biomes. I'll update 1.12 versions to support it, but I don't know whether WE will update for it in 1.12 versions.

To economize space though, it might be considered that 3d biomes be supported by a particular data version origin of the schematic compared to the schematic version, and this is what I mean:

Biomes in pre 1.15 are 2d, so adding the extra y-layer would add some overhead cost of storage for all older schematics and new schematics made, when there's no benefit of them being stored, we can get away with some "hackery" to support it by checking the data version, and then on the version flip to storing y values as well as x and z. On importing data, the data version should always be checked regardlessly, but we could in theory support importing 3d biome data into previous versions, omitting the y layers and reading the bottom most tile.. maybe....

I'm open for opinions on how the feature would be implemented or suggested implementation since a forwards/backwards version is somewhat required.

**Comment by devmattrick** [comment]
I looked a bit more into this after posting this issue and there were some problems I noticed.

For one, biomes are always chunk aligned but schematics aren't. This isn't an issue with 1x256x1 biome maps, but since the new biomes are 4x4x4 we can end up with a situation where when pasting the schematic if its not aligned to a chunk boundary, the biome map will be misaligned.

Another issue I noticed was in the overworld (at least as of 1.15), 3D biomes aren't a thing. The data storage format is in 3D but the game only respects the bottom most layer of biomes. I have a feeling this will change eventually, though.

Finally, when importing pre-3D biome schematics since you're mapping from 1x256x1 to 4x4x4, you'll need to somehow "sample" the biomes. For example, in a 4x4 section you used to be able to have 4 biomes but now you can only have 1 so how do you select the biome to actually apply? Should the spec define how this should work for consistency?
