### ISSUE TITLE
Entity Object specification missing

### ISSUE THREAD

**Issue by octylFractal** [SpongePowered/Schematic-Specification#7]
I assume it's the same as `TileEntity` except with a list of double tags instead of an int array tag, but it'd probably be a good idea to put it in the specification.

**Comment by Deamon5550** [comment]
I removed Entities from the first version of the spec because I didn't support them in the implementation I wrote and they need a bit more thought from an API perspective.

**Comment by octylFractal** [comment]
Then you should remove it from the list of fields.

**Comment by Deamon5550** [comment]
Oh derp missed that one thanks.

**Comment by Michel-0** [comment]
I request to reopen the issue.

A specification is independent of "the implementation you wrote".
When defining a standard for the global world, you can't think of something you already implemented. You need to think of what's best for the standard everyone will use.
I'm about to write an library to create sponge schematics and i'll include entities for sure.

That's why i hereby request to add the Entity[] to the specification version 2.

Greetings,
Michel-0
